### ISSUE TITLE
Add progressive level loading on `Normal` mode game start and on subsequent `Next Level` button presses

### ISSUE THREAD

**Issue by LukeDarling** [bjucps209/spring2021-team3#20]
When the player clicks `Play`, check the game mode drop down.

- If the player selected `Normal` mode, load built-in level 1. On subsequent `Next Level` button presses at the end of each level, load the next available built-in numbered level. If there are no more progressive built-in levels, set the game state to `GAME_OVER`, set the lose message to something appropriate for winning, and execute `gameLoop.play();`.
- If the player selected `Custom` mode, load the selected custom level as usual.

**Comment by BunnyHog793** [comment]
Should work now, though i couldn't figure out how to make the score stay between levels, it keeps resetting to zero

**Comment by BunnyHog793** [comment]
Nevermind, i fixes it!
